In [29]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [30]:
# Read the dataset
dataset = pd.read_csv('Data.csv')

In [31]:
# Memilih fitur dan target yang akan digunakan
# ===============================
x = dataset[['Country', 'Age', 'Salary']].values

# Memilih label
y = dataset['Purchased'].values

In [32]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Russia' 40.0 50000.0]
 ['Indonesia' 32.0 47000.0]
 ['Indonesia' 29.0 95000.0]
 ['Australia' 47.0 98000.0]
 ['China' 33.0 77000.0]
 ['Australia' 31.0 nan]
 ['Russia' 41.0 50000.0]
 ['France' 38.0 93000.0]
 ['Germany' 47.0 91000.0]
 ['Russia' nan 89000.0]
 ['China' 28.0 75000.0]
 ['Spain' 27.0 nan]
 ['China' 35.0 80000.0]
 ['China' 34.0 78000.0]
 ['Australia' 29.0 72000.0]
 ['Spain' 24.0 50000.0]
 ['Germany' nan 97000.0]
 ['Indonesia' 36.0 59000.0]
 ['Germany' 31.0 nan]
 ['Australia' 43.0 47000.0]]


In [33]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No'
 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'No' 'Yes' 'No' 'Yes']


In [34]:
# Mengisi atribut yang kosong menggunakan nilai rata-rata(mean) dengan SimpleImputer
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [35]:
# Cek kembali value setelah atribut yang sebelumnya kosong diberikan nilai rata-rata
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 70076.92307692308]
 ['France' 35.0 58000.0]
 ['Spain' 36.074074074074076 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Russia' 40.0 50000.0]
 ['Indonesia' 32.0 47000.0]
 ['Indonesia' 29.0 95000.0]
 ['Australia' 47.0 98000.0]
 ['China' 33.0 77000.0]
 ['Australia' 31.0 70076.92307692308]
 ['Russia' 41.0 50000.0]
 ['France' 38.0 93000.0]
 ['Germany' 47.0 91000.0]
 ['Russia' 36.074074074074076 89000.0]
 ['China' 28.0 75000.0]
 ['Spain' 27.0 70076.92307692308]
 ['China' 35.0 80000.0]
 ['China' 34.0 78000.0]
 ['Australia' 29.0 72000.0]
 ['Spain' 24.0 50000.0]
 ['Germany' 36.074074074074076 97000.0]
 ['Indonesia' 36.0 59000.0]
 ['Germany' 31.0 70076.92307692308]
 ['Australia' 43.0 47000.0]]


In [36]:
# Mengubah kolom "Country" ke dalam bentuk matriks menggunakan ColumnTransfer dan OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [37]:
# Cek kolom "Country" setelah diubah ke dalam bentuk matriks
print(x)

# Setelah dataset dimodifikasi, teradapat 30 baris data

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 40.0 70076.92307692308]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 36.074074074074076 52000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.0 50000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 32.0 47000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 29.0 95000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 47.0 98000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 33.0 77000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 31.0 70076.92307692308]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 41.0 50000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 38.0 93000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 47.0 91000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 36.074074074074076 89000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 28.0 75000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.

In [38]:
# Mengubah value label "Purchase" ke dalam bentuk matriks menggunakan LabelEncoder
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [39]:
# Cek value label setelah diubah ke dalam bentuk matriks
print(y)

[0 1 0 0 1 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 1 0 1 0 1 0 0 1 0 1]


In [40]:
# Melakukan train test split dengan test_size sebesar 20%
from sklearn.model_selection import train_test_split

# Split 24:6
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [41]:
# Cek banyak data yang digunakan untuk training
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 36.074074074074076 97000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 29.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 35.0 80000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 34.0 78000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 40.0 70076.92307692308]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 24.0 50000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 36.074074074074076 52000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 47.0 91000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 47.0 98000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 36.0 59000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 41.0 50000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 31.0 70076.92307692308]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 43.0 47000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 31.0 70076.92307692308]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 0.0 

In [42]:
# Cek banyak data yang digunakan untuk testing
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 38.0 93000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 27.0 70076.92307692308]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.0 50000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 36.074074074074076 89000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 33.0 77000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 28.0 75000.0]]


In [43]:
# Cek banyak label yang digunakan untuk training
print(y_train)

[0 0 1 1 0 1 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0 0 0 1]


In [44]:
# Cek banyak label yang digunakan untuk testing
print(y_test)

[0 0 0 1 1 1]


In [45]:
# Scaling
from sklearn.preprocessing import StandardScaler

# Hanya diterapkan kepada x_train dan x_test
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])


In [46]:
print(x_train)

[[0.0 0.0 0.0 1.7320508075688774 -0.3779644730092272 -0.2085144140570747
  -0.447213595499958 -0.08608330869900917 1.7571307273816958]
 [0.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.2085144140570747
  2.2360679774997902 0.19080321000295794 -0.4762168260811541]
 [1.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.2085144140570747
  -0.447213595499958 -1.103108790854313 0.20619492636582784]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.2085144140570747
  -0.447213595499958 -0.240500790282799 0.7024943826909056]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.2085144140570747
  -0.447213595499958 -0.3842687903780513 0.5784195186096361]
 [0.0 0.0 0.0 1.7320508075688774 -0.3779644730092272 -0.2085144140570747
  -0.447213595499958 0.4783392101934626 0.08689217244153037]
 [0.0 0.0 0.0 1.7320508075688774 -0.3779644730092272 -0.2085144140570747
  -0.447213595499958 -0.9593407907590605 -0.9104788503655972]
 [0.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 -0

In [47]:
print(x_test)

[[0.0 0.0 1.0 -0.5773502691896258 -0.3779644730092272 -0.2085144140570747
  -0.447213595499958 0.19080321000295794 1.508980999219157]
 [0.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.2085144140570747
  2.2360679774997902 -1.3906447910448174 0.08689217244153037]
 [0.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 4.795831523312718
  -0.447213595499958 0.4783392101934626 -1.158628578528136]
 [0.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 4.795831523312718
  -0.447213595499958 -0.08608330869900917 1.260831271056618]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.2085144140570747
  -0.447213595499958 -0.5280367904733037 0.5163820865690014]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.2085144140570747
  -0.447213595499958 -1.2468767909495653 0.392307222487732]]
